version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./pg_env
    volumes:
      - ./persistentdata/postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'
