version: '3.8'
services:

  nest:
    depends_on:
      - postgres
    build:
      context: ./app
    command: "npm run start"
    ports:
      - "8000:8000"
    volumes:
      - ./persistentdata/uploads:/app/uploads

  postgres:
    image: postgres
    restart: always
    env_file:
      - ./postgres/.pg_env
    volumes:
      - ./persistentdata/postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'
